name: u_coin
description: "Project was to see price money"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  dio: ^5.0.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2  
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  connectivity_plus: ^6.0.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo_app.png
    - assets/splash_screen.png
flutter_native_splash:
  color: "#141414" # cor de fundo
  image: assets/splash_screen.png
  android: true
  ios: true
  fullscreen: true
