// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgPJ4BOU0_GC9ytEz1vPl1H0f5z54wlps',
    appId: '1:537600878721:web:e8495905249411e76c8580',
    messagingSenderId: '537600878721',
    projectId: 'ucoin-flutter',
    authDomain: 'ucoin-flutter.firebaseapp.com',
    storageBucket: 'ucoin-flutter.firebasestorage.app',
    measurementId: 'G-T43TPKVQZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9e4z3IwTH3ZOxSVCRxG7BQU6xxNbtOa8',
    appId: '1:537600878721:android:18c4bb5817d471ca6c8580',
    messagingSenderId: '537600878721',
    projectId: 'ucoin-flutter',
    storageBucket: 'ucoin-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCldLD26tCcDeHFE2pYA-2lLNWBpPCT55k',
    appId: '1:537600878721:ios:fe7acd12034425f16c8580',
    messagingSenderId: '537600878721',
    projectId: 'ucoin-flutter',
    storageBucket: 'ucoin-flutter.firebasestorage.app',
    iosBundleId: 'com.ucoin.uCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCldLD26tCcDeHFE2pYA-2lLNWBpPCT55k',
    appId: '1:537600878721:ios:fe7acd12034425f16c8580',
    messagingSenderId: '537600878721',
    projectId: 'ucoin-flutter',
    storageBucket: 'ucoin-flutter.firebasestorage.app',
    iosBundleId: 'com.ucoin.uCoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgPJ4BOU0_GC9ytEz1vPl1H0f5z54wlps',
    appId: '1:537600878721:web:6e0abe42cbeeee9b6c8580',
    messagingSenderId: '537600878721',
    projectId: 'ucoin-flutter',
    authDomain: 'ucoin-flutter.firebaseapp.com',
    storageBucket: 'ucoin-flutter.firebasestorage.app',
    measurementId: 'G-TTY0NTFPG3',
  );
}
